MERGE INTO `${target_table}` AS T
USING (
  WITH
    S0 AS (
      SELECT * FROM `${source_table}`
      WHERE Recordstamp >= (
        SELECT IFNULL(MAX(Recordstamp), TIMESTAMP('1940-12-25 05:30:00+00'))
        FROM `${target_table}`)
    ),
    -- To handle accidental dups from sfdc extraction
    S1 AS (
      SELECT * EXCEPT(row_num)
      FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY UserId, Recordstamp ORDER BY Recordstamp) AS row_num
        FROM S0
      )
      WHERE row_num = 1
    ),
    T1 AS (
      SELECT UserId, MAX(Recordstamp) AS Recordstamp
      FROM `${source_table}`
      WHERE Recordstamp >= (
        SELECT IFNULL(MAX(Recordstamp), TIMESTAMP('1940-12-25 05:30:00+00'))
        FROM `${target_table}`)
      GROUP BY UserId
    )
  SELECT S1.*
  FROM S1
  INNER JOIN T1
    ON S1.UserId = T1.UserId
      AND S1.Recordstamp = T1.Recordstamp
  ) AS S
ON T.UserId = S.UserId
WHEN NOT MATCHED AND IFNULL(S.OperationalFlag, 'I') != 'D' THEN
  INSERT (
    `UserId`,
    `AboutMe`,
    `AccountId`,
    `Alias`,
    `BadgeText`,
    `BannerPhotoUrl`,
    `CallCenterId`,
    `City`,
    `CommunityNickname`,
    `CompanyName`,
    `ContactId`,
    `Country`,
    `CreatedById`,
    `CreatedDatestamp`,
    `DefaultGroupNotificationFrequency`,
    `DelegatedApproverId`,
    `Department`,
    `DigestFrequency`,
    `Division`,
    `Email`,
    `EmailEncodingKey`,
    `EmailPreferencesAutoBcc`,
    `EmployeeNumber`,
    `Extension`,
    `Fax`,
    `FederationIdentifier`,
    `FirstName`,
    `ForecastEnabled`,
    `FullPhotoUrl`,
    `GeocodeAccuracy`,
    `IndividualId`,
    `IsActive`,
    `IsProfilePhotoActive`,
    `LanguageLocaleKey`,
    `LastLoginDatestamp`,
    `LastModifiedById`,
    `LastModifiedDatestamp`,
    `LastName`,
    `LastReferencedDatestamp`,
    `LastViewedDatestamp`,
    `Latitude`,
    `LocaleSidKey`,
    `Longitude`,
    `ManagerId`,
    `MediumBannerPhotoUrl`,
    `MediumPhotoUrl`,
    `MobilePhone`,
    `Name`,
    `Phone`,
    `PostalCode`,
    `ProfileId`,
    `SenderEmail`,
    `SenderName`,
    `Signature`,
    `SmallBannerPhotoUrl`,
    `SmallPhotoUrl`,
    `State`,
    `Street`,
    `SystemModstamp`,
    `TimeZoneSidKey`,
    `Title`,
    `UserName`,
    `UserRoleId`,
    `UserType`,
    `Recordstamp`)
  VALUES (
    `UserId`,
    `AboutMe`,
    `AccountId`,
    `Alias`,
    `BadgeText`,
    `BannerPhotoUrl`,
    `CallCenterId`,
    `City`,
    `CommunityNickname`,
    `CompanyName`,
    `ContactId`,
    `Country`,
    `CreatedById`,
    `CreatedDatestamp`,
    `DefaultGroupNotificationFrequency`,
    `DelegatedApproverId`,
    `Department`,
    `DigestFrequency`,
    `Division`,
    `Email`,
    `EmailEncodingKey`,
    `EmailPreferencesAutoBcc`,
    `EmployeeNumber`,
    `Extension`,
    `Fax`,
    `FederationIdentifier`,
    `FirstName`,
    `ForecastEnabled`,
    `FullPhotoUrl`,
    `GeocodeAccuracy`,
    `IndividualId`,
    `IsActive`,
    `IsProfilePhotoActive`,
    `LanguageLocaleKey`,
    `LastLoginDatestamp`,
    `LastModifiedById`,
    `LastModifiedDatestamp`,
    `LastName`,
    `LastReferencedDatestamp`,
    `LastViewedDatestamp`,
    `Latitude`,
    `LocaleSidKey`,
    `Longitude`,
    `ManagerId`,
    `MediumBannerPhotoUrl`,
    `MediumPhotoUrl`,
    `MobilePhone`,
    `Name`,
    `Phone`,
    `PostalCode`,
    `ProfileId`,
    `SenderEmail`,
    `SenderName`,
    `Signature`,
    `SmallBannerPhotoUrl`,
    `SmallPhotoUrl`,
    `State`,
    `Street`,
    `SystemModstamp`,
    `TimeZoneSidKey`,
    `Title`,
    `UserName`,
    `UserRoleId`,
    `UserType`,
    `Recordstamp`)
WHEN MATCHED AND S.OperationalFlag = 'D' THEN
  DELETE
WHEN MATCHED AND S.OperationalFlag = 'U' THEN
  UPDATE SET
    T.`UserId` = S.`UserId`,
    T.`AboutMe` = S.`AboutMe`,
    T.`AccountId` = S.`AccountId`,
    T.`Alias` = S.`Alias`,
    T.`BadgeText` = S.`BadgeText`,
    T.`BannerPhotoUrl` = S.`BannerPhotoUrl`,
    T.`CallCenterId` = S.`CallCenterId`,
    T.`City` = S.`City`,
    T.`CommunityNickname` = S.`CommunityNickname`,
    T.`CompanyName` = S.`CompanyName`,
    T.`ContactId` = S.`ContactId`,
    T.`Country` = S.`Country`,
    T.`CreatedById` = S.`CreatedById`,
    T.`CreatedDatestamp` = S.`CreatedDatestamp`,
    T.`DefaultGroupNotificationFrequency` = S.`DefaultGroupNotificationFrequency`,
    T.`DelegatedApproverId` = S.`DelegatedApproverId`,
    T.`Department` = S.`Department`,
    T.`DigestFrequency` = S.`DigestFrequency`,
    T.`Division` = S.`Division`,
    T.`Email` = S.`Email`,
    T.`EmailEncodingKey` = S.`EmailEncodingKey`,
    T.`EmailPreferencesAutoBcc` = S.`EmailPreferencesAutoBcc`,
    T.`EmployeeNumber` = S.`EmployeeNumber`,
    T.`Extension` = S.`Extension`,
    T.`Fax` = S.`Fax`,
    T.`FederationIdentifier` = S.`FederationIdentifier`,
    T.`FirstName` = S.`FirstName`,
    T.`ForecastEnabled` = S.`ForecastEnabled`,
    T.`FullPhotoUrl` = S.`FullPhotoUrl`,
    T.`GeocodeAccuracy` = S.`GeocodeAccuracy`,
    T.`IndividualId` = S.`IndividualId`,
    T.`IsActive` = S.`IsActive`,
    T.`IsProfilePhotoActive` = S.`IsProfilePhotoActive`,
    T.`LanguageLocaleKey` = S.`LanguageLocaleKey`,
    T.`LastLoginDatestamp` = S.`LastLoginDatestamp`,
    T.`LastModifiedById` = S.`LastModifiedById`,
    T.`LastModifiedDatestamp` = S.`LastModifiedDatestamp`,
    T.`LastName` = S.`LastName`,
    T.`LastReferencedDatestamp` = S.`LastReferencedDatestamp`,
    T.`LastViewedDatestamp` = S.`LastViewedDatestamp`,
    T.`Latitude` = S.`Latitude`,
    T.`LocaleSidKey` = S.`LocaleSidKey`,
    T.`Longitude` = S.`Longitude`,
    T.`ManagerId` = S.`ManagerId`,
    T.`MediumBannerPhotoUrl` = S.`MediumBannerPhotoUrl`,
    T.`MediumPhotoUrl` = S.`MediumPhotoUrl`,
    T.`MobilePhone` = S.`MobilePhone`,
    T.`Name` = S.`Name`,
    T.`Phone` = S.`Phone`,
    T.`PostalCode` = S.`PostalCode`,
    T.`ProfileId` = S.`ProfileId`,
    T.`SenderEmail` = S.`SenderEmail`,
    T.`SenderName` = S.`SenderName`,
    T.`Signature` = S.`Signature`,
    T.`SmallBannerPhotoUrl` = S.`SmallBannerPhotoUrl`,
    T.`SmallPhotoUrl` = S.`SmallPhotoUrl`,
    T.`State` = S.`State`,
    T.`Street` = S.`Street`,
    T.`SystemModstamp` = S.`SystemModstamp`,
    T.`TimeZoneSidKey` = S.`TimeZoneSidKey`,
    T.`Title` = S.`Title`,
    T.`UserName` = S.`UserName`,
    T.`UserRoleId` = S.`UserRoleId`,
    T.`UserType` = S.`UserType`,
    T.Recordstamp = S.Recordstamp;
